config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users, controllers: { sessions: 'users/sessions' }
  resources :meetings
  post '/meetings/new', to: 'meetings#create'
  resources :comments
  post '/meetings/:id', to: 'comments#create'
  
  root "homes#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :meeting

  validates :comment, presence: true
end

app/models/delayed_job.rb
class DelayedJob < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  belongs_to :user
  has_many :comments, dependent: :destroy

  validates :title, presence: true
  validate :end_after_start
  validates :start_time, :end_time, :presence => true, :overlap => {:scope => "user_id"}

  scope :tomorrow_meetings, -> { where(start_time: Date.tomorrow.beginning_of_day .. Date.tomorrow.end_of_day) }

  private
  def end_after_start
    return if end_time.blank? || start_time.blank?
  
    if end_time <= start_time
      errors.add(:end_time, "must be after the start time") 
    end 
  end
end

app/models/payment_card.rb
class PaymentCard < ApplicationRecord
  belongs_to :user  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :meetings, dependent: :destroy
  has_many :comments, through: :meetings, dependent: :destroy
  has_many :payment_cards, dependent: :destroy

  validates :phone, phone: true

  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  def admin?
    AdminUser.find_by(email: self.email) ? true : false
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  def after_sign_in_path_for(resource)
    stored_location_for(resource) || meetings_path
  end

  protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone])
    devise_parameter_sanitizer.permit(:account_update, keys: [:phone])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    comment = Comment.new(comment_params)
    meeting = Meeting.find(params[:comment][:meeting_id].to_i)
    if comment.save
      flash[:notice] = "Comments added successfully!"
      redirect_to meeting_path(meeting)
    else
      flash[:alert] = "Error adding Comments!"
      redirect_to meeting_path(meeting)
    end
  end


  def destroy
    comment = Comment.find(params[:id])
    meeting = Meeting.find(comment.meeting_id)
    if comment.destroy
      flash[:notice] = "Successfully deleted comment!"
      redirect_to meeting_path(meeting)
    else
      flash[:alert] = "Error deleting comment!"
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:comment, :user_id, :meeting_id)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :authenticate_user!

  def index
    if current_user.admin?
      meeting = Meeting.all
    else
      meeting = current_user.meetings
    end
    @meetings = meeting.order('start_time')
    @todays_meeting = @meetings.select {|x| x.start_time.day == Time.current.day}
    @upcoming_meeting = @meetings.select {|x| x.start_time.day > Time.current.day}
    @completed_meeting = @meetings.select {|x| x.start_time.day < Time.current.day}
  end

  def new 
    @meeting = Meeting.new
  end

  def create
    @meeting = Meeting.new(meeting_params)
    @meeting.user_id = current_user.id

    token = params[:stripeToken]
    card_brand = params[:payment_card][:card_brand]
    card_exp_month = params[:payment_card][:card_exp_month]
    card_exp_year = params[:payment_card][:card_exp_year]
    card_last4 = params[:payment_card][:card_last4]
    Stripe.api_key = Rails.application.secrets.stripe_api_key

    charge = Stripe::Charge.create(
      amount: 50000,
      currency: "inr",
      description: "Meeting charges",
      source: token
    )

    card = PaymentCard.find_or_initialize_by(card_last4: params[:payment_card][:card_last4])
    card.user_id = @meeting.user_id
    card.stripe_id = charge.id
    card.card_brand = card_brand
    card.card_exp_month = card_exp_month
    card.card_exp_year = card_exp_year
    card.card_last4 = card_last4
    # card.save!

    if @meeting.save && card.save
      message = "Hey, you have booked #{@meeting.title} meeting. The meeting is at #{@meeting.start_time.strftime("%I:%M%p")} on #{@meeting.start_time.to_date} date"
      TwilioClient.new.send_text(@meeting.user, message)
      redirect_to @meeting, notice: 'Meeting was successfully created.'
    else
      flash[:alert] = @meeting.errors.full_messages.first
      render :new
    end

    rescue Stripe::CardError => e
      flash.alert = e.message
      render action: :new
  end
 
  def show
    @meeting = Meeting.find(params[:id])
    @comments = @meeting.comments.all
    @comment = Comment.new
  end

  def destroy
    @meeting = Meeting.find(params[:id])
    if @meeting.destroy
      flash[:notice] = "Successfully deleted meeting!"
      redirect_to meetings_path
    else
      flash[:alert] = "Error deleting meeting!"
      redirect_to meetings_path
    end
  end

  private
  def meeting_params
    params.require(:meeting).permit(:title, :start_time, :end_time, :user_id)
  end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/homes/index.html.erb
<div class="card text-center" style="width: 50%; margin-left:25%; margin-top:5%">
  <div class="card-body">
    <h2 class="card-title">Welcome!</h2>
    <% if user_signed_in? %>
      Logged in as <strong><%= current_user.email %></strong>.
      <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <p>Register to get started.</p>
      <%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MeetingScheduling</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= tag :meta, name: "stripe-public-key", content: Rails.application.secrets.stripe_publishable_key %>
  </head>

  <body>
  
    <nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #1a1818">
      <div class="container-fluid">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">

            <li class="nav-item">
              <%= link_to "Home", root_path, :class => 'nav-link active fs-5 pr-3' %>
            </li>

            <% if user_signed_in? %>
              <li class="nav-item">
                <%= link_to "Meetings", meetings_path, :class => 'nav-link fs-5 pr-3' %>
              </li>
              <li class="nav-item">
                <%= link_to "New Meeting", new_meeting_path, :class => 'nav-link fs-5 pr-3' %>
              </li>
            </ul>
              <form class="d-flex">
                <li><%= link_to "Log out", '/users/sign_out', :class => 'btn btn-primary btn-group-sm border border-secondary fs-5', :method => :delete %></li>
              </form>

            <% else %>
          </ul>
            <form class="d-flex">
              <li><%= link_to "Sign up", new_user_registration_path , :class => 'btn btn-primary btn-group-sm border border-secondary fs-5' %></li>
              <li><%= link_to "Log in", new_user_session_path, :class => 'btn btn-primary btn-group-sm border border-secondary fs-5' %></li>
            </form>
            <% end %>
        </div>
      </div>
    </nav>

    <!-- displaying flash messages -->
    <% flash.each do |key, value| %>
      <% if key=alert %>
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
          <%= value %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% else %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">
          <%= value %>
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/meetings/_payment.html.erb
<html lang="en">
  <head>
    <script src="https://js.stripe.com/v3/"></script>
    <!-- <%= stylesheet_link_tag 'checkout.css' %> -->
    <%= javascript_pack_tag 'checkout', 'data-turbolinks-track': 'reload'%>
  </head>
  <body>
    <div class="d-flex mt-2">
      <div>
        <%= image_tag "card.png", class: "img-fluid mt-2", style: "width:25px" %>
      </div>
      <div class="card mt-2 ms-1 border-dark" style="width: 30rem;">
        <div class="card-body">
          <div class="mb-6 relative">
            <label for="card-element" class="label">
              Enter credit or debit card. All meetings cost ₹300 INR.
            </label>

            <div id="card-element" class="input my-1">
              <!-- a Stripe Element will be inserted here. -->
            </div>
            <!-- used to display Element errors -->
            <div id="card-errors" role="alert"></div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/meetings/index.html.erb
<div class='my-5'>
  <div class="col-xl-4 col-lg-6 col-md-8 col-sm-10 mx-auto form p-4 bg-light border border-1 rounded-3" style="width:750px">

    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <button class="nav-link active fs-5" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Calendar</button>
      </li>
      <li class="nav-item" role="presentation">
        <button class="nav-link fs-5" id="pills-profile-tab" data-bs-toggle="pill" data-bs-target="#pills-profile" type="button" role="tab" aria-controls="pills-profile" aria-selected="false">All Meetings</button>
      </li>
    </ul>

    <div class="tab-content" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <%= month_calendar events: @meetings do |date, meetings| %>
          <%= date %>
          <% meetings.each do |meeting| %>
            <div class="border border-1 rounded-2 mb-1 overflow-hidden" style="background-color: #deebf1; height:20px; padding-bottom:25px">
              <%= link_to meeting.title, meeting, class: "link", style: "font-size:14px; text-decoration: none; color:#243dbd" %>
            </div>
          <% end %>
        <% end %>
      </div>

      <div class="tab-pane fade overflow-auto" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab" style="height:537px">
        <p>Today : </p>
        <% @todays_meeting.each do |meeting| %>
          <div class="bg-white border border-1 rounded-3 my-2 p-2">
            <li class="nav-item" style="list-style:none">
              <%= link_to meeting.title, meeting_path(meeting),style: "text-decoration: none; color:black"%><br>
              <p style='margin-bottom:0; font-size:12px'><%= meeting.start_time.strftime( '%d/%m/%Y') %> (<%= meeting.start_time.strftime("%I:%M%p") %>) -----> <%= meeting.end_time.strftime( '%d/%m/%Y') %> (<%= meeting.end_time.strftime("%I:%M%p") %>)</p>
            </li>
          </div>
        <% end %>
        <p>Upcoming : </p>
        <% @upcoming_meeting.each do |meeting| %>
          <div class="bg-white border border-1 rounded-3 my-2 p-2">
            <li class="nav-item" style="list-style:none">
              <%= link_to meeting.title, meeting_path(meeting),style: "text-decoration: none; color:black"%><br>
              <p style='margin-bottom:0; font-size:12px'><%= meeting.start_time.strftime('%d/%m/%Y') %> (<%= meeting.start_time.strftime("%I:%M%p") %>) -----> <%= meeting.end_time.strftime('%d/%m/%Y') %> (<%= meeting.end_time.strftime("%I:%M%p") %>)</p>
            </li>
          </div>
        <% end %>
        <p>Completed : </p>
        <% @completed_meeting.each do |meeting| %>
          <div class="bg-white border border-1 rounded-3 my-2 p-2">
            <li class="nav-item" style="list-style:none">
              <%= link_to meeting.title, meeting_path(meeting),style: "text-decoration: none; color:black"%><br>
              <p style='margin-bottom:0; font-size:12px'><%= meeting.start_time.strftime('%d/%m/%Y') %> (<%= meeting.start_time.strftime("%I:%M%p") %>) -----> <%= meeting.end_time.strftime('%d/%m/%Y') %> (<%= meeting.end_time.strftime("%I:%M%p") %>)</p>
            </li>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/meetings/new.html.erb
<div class="fluid p-3"> 
  <%= form_with(model: @meeting, local: true, class: "meeting-form") do |form| %>

    <h3 class="mb-4 border-secondary" style="border-bottom:2px solid">Meeting Information</h3>

    <div class="mb-6">
      <%= image_tag "edit.png", class: "img-fluid" %>
      <%= form.text_field :title, class: "input", placeholder: "Add Title" %>
    </div>

      <%= form.number_field :user_id, value: current_user.id, type: :hidden %>

      <div class="flex items-center justify-between max-w-md mt-3">
        <%= image_tag "time.png", class: "img-fluid", style: "width:25px" %>
        <%= form.datetime_select :start_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 5 }, { class: "select py-2 px-2 mr-2" } %> ----->
        <%= form.datetime_select :end_time, { start_day: Date.today, start_year: Date.today.year, minute_step: 5 }, { class: "select py-2 px-2 mr-2" } %>
      </div>


    <%= render "payment.html.erb" %>

    <%= form.submit class: "text-base py-1 px-2 my-3 ms-4" %>
  <% end %>
</div>
<%= link_to 'back', meetings_path, class: "ms-3", style: "text-decoration:none" %>

app/views/meetings/show.html.erb
<div class="container border border-secondary mt-5 pt-3 ms-5" style="width:30%; background-color:#ebeaea">
  <div>
    <h3><%= @meeting.title %></h3>
    <p style="font-size:15px"><%= @meeting.start_time.strftime('%d/%m/%Y') %> (<%= @meeting.start_time.strftime("%I:%M%p") %>) -----> <%= @meeting.end_time.strftime('%d/%m/%Y') %> (<%= @meeting.end_time.strftime("%I:%M%p") %>)</p>
    <li class="nav-item" style="list-style:none">
      <%= link_to 'Delete', meeting_path(@meeting), class: 'btn btn-dark btn-sm', method: :delete, data: {confirm: 'Are you sure?'} %>
    </li>
  </div>
  
  <div class="bg-white p-2 my-2 rounded-3">
    <h4>Comments :</h4>
    <div class="mt-1 overflow-auto" style="height:200px; width:100%">
      <% @comments.each do |comment| %>
        <div class="d-flex border border-1 mb-1">
          <div class="flex-grow-1 ps-2"><%= comment.comment %></div>
          <div><%= link_to image_tag("delete.png", class: 'img-fluid', style: "width:15px"),comment_path(comment), method: :delete, data: {confirm: 'Are you sure?'} %></div>
        </div>  
      <% end %>
    </div>

    <div class="mt-5 mx-2">
      <%= form_for @comment, html: { multipart: true } do |f| %>

        <div class="form-group">
          <%= f.number_field :user_id, class: 'form-control', value: current_user.id, type: :hidden %>
        </div>

        <div class="form-group">
          <%= f.number_field :meeting_id, class: 'form-control', value: @meeting.id , type: :hidden %>
        </div>

        <div class="form-group d-flex" style="width:100%">
          <%= f.text_field :comment, class: 'form-control flex-grow-1', placeholder: "Write Comment" %>
          <%= f.submit 'Add comment' %>
        </div>
      <% end %>
    </div>
  </div>
</div>
<p class='mt-1 ms-5'><%= link_to 'back', meetings_path , style: "text-decoration:none" %></p>

app/views/simple_calendar/_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <%= content_tag :tr, class: calendar.tr_classes_for(week) do %>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        <% end %>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_month_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading mb-2">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <span class="calendar-title"><%= t('date.month_names')[start_date.month] %> <%= start_date.year %></span>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped bg-white">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, style: "font-size:15px; margin-top:0", class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day.day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day.day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/simple_calendar/_week_calendar.html.erb
<div class="simple-calendar">
  <div class="calendar-heading">
    <%= link_to t('simple_calendar.previous', default: 'Previous'), calendar.url_for_previous_view %>
    <% if calendar.number_of_weeks == 1 %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %></span>
    <% else %>
      <span class="calendar-title"><%= t('simple_calendar.week', default: 'Week') %> <%= calendar.week_number %> - <%= calendar.end_week %></span>
    <% end %>
    <%= link_to t('simple_calendar.next', default: 'Next'), calendar.url_for_next_view %>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <% date_range.slice(0, 7).each do |day| %>
          <th><%= t('date.abbr_day_names')[day.wday] %></th>
        <% end %>
      </tr>
    </thead>

    <tbody>
      <% date_range.each_slice(7) do |week| %>
        <tr>
          <% week.each do |day| %>
            <%= content_tag :td, class: calendar.td_classes_for(day) do %>
              <% if defined?(Haml) && respond_to?(:block_is_haml?) && block_is_haml?(passed_block) %>
                <% capture_haml(day, sorted_events.fetch(day, []), &passed_block) %>
              <% else %>
                <% passed_block.call day, sorted_events.fetch(day, []) %>
              <% end %>
            <% end %>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>